# Generated by Django 4.1.7 on 2023-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название')),
                ('product_category', models.CharField(choices=[('Category_1', 'Категория_1'), ('Category_2', 'Категория_2'), ('Category_3', 'Категория_3')], default='Category_1', max_length=15, verbose_name='Категория')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('product_image', models.ImageField(default='default/placeholder.png', upload_to='product', verbose_name='Картинка')),
            ],
        ),
    ]
