# Generated by Django 4.1.7 on 2023-03-25 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Отзыв')),
                ('review_grade', models.PositiveSmallIntegerField(max_length=1, verbose_name='Оценка')),
                ('review_author', models.ManyToManyField(related_name='review_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('review_product', models.ManyToManyField(related_name='review_product', to='reviews.product', verbose_name='Продукт')),
            ],
        ),
    ]
